language: node_js
node_js:
  - "4.1"

before_install:
  - npm install -g gulp
  - gulp -v
  - wget https://releases.hashicorp.com/terraform/0.9.0/terraform_0.9.0_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

install:
  - npm install

script:
  - gulp build
  - terraform init infra
  - terraform apply infra

env:
  global:
    - secure: U+PDZEiYCAS6U1vFtbdB9XtgNjwYrUue14QWd5FTu5KznemGNH9XyZy6J/eR3YzZKyPP7x3NtLXa85d9gOZ7eWo+qx8a6IjmZjKPaAEiQ78dSipEv+mFFMvBI3ZjZ8pdTqzYDkvCViXr+89KffqfFS43vPgVYDxFfzwat9fUMvnb08FPiHfaIlkPmmiuXaW2rwQrVYHy0w/vba3OJlNCJIjfxdwg7BH5bNNKDSupmnRq1SomROOhBVIh110YgYxGrkkPemjyK6fEhvHreOWiWvd0IZmUlwqMu8P6QrgJuxlY/2sdozTdkw/zXKHRU1aeZ3A0IOzodmDS4Uc157eLZXAwL4bMwk0TJ4PGNx/KjLbPwC/ujOpNU7POAv+72zoeiJy5wI1OA59yYvw5BaB982/NeMz2xOdxODKAc6K+Kp08vIx12NLjpSwLi8NyuLI/NkaAGHmPPRm64Ea7qRMvO3xULxBtVU6iJeWsb1n802iF2T7EnT3s0s51WL/nXXqZRqvqGLbFWz27PLE6naRhbAMrLlYXNU274gNhgMiNCqm4e8DJAQiMewHm1d4bCVrjtPXI3wh5Vb0u9XZa29DMqgiXQxl4qqRqlgYKpN5jYDEOqQ2qXomG06jgaTqBO2vZ5Y0I6jVkKjRNGSdKyEcMawtyD3LWRVar2Jxyk7ebOaI=
    - secure: ieyXK5UW+hOEvZM4j/tVQcpi4ija/opXa+1HoIpwhrwLy77UvIiEXmFnT2zEFBex5a1RsZCvD4pL0LNSyphsTeAgNnYaj327xGAPhmv+ybVubg05D8LsZS2+fNuYlq2i8ce/QGWdN5surIY0neka4ydI6nPqqHAn5Yacx2mDxHYhAV9YHzdzvp2HqtRiE8MC7oRIpOAmrxSN79XSKObZbBP69B1lCKmZM4Hep6Lb4+rfx9r39xIFkEj2JvQGPe4wvseeXFolNXiB6xa0jeWQwVti6rNeUEVOlsVMdEdMOBUcjlpIdGpn2ZfDKdpPH5/3tu8MxJ+sozBw4Wh7CK7JiYJSOA/wzXSRT+QI9DtEFthxKZhej2kyjyHVrZod+Lzk7mI12FuGQIHGAbJpRGyOeRYt5S8IEEVbecP2efU51en4mzyX5soTjkLh0cx7ja8toiMMsDrfiFKYh0s4m/QN6jKrsZuFQctOvS6e7wj4dxi4xNiNuaKLfqlWd1LVc1S9Xfm7LpPUNleunzQfUkyJ6K1mxHWMl/PUJ5krSW3W+R6cs5qo8dSCZUVKPHHTPO+RtNrERlsHaHXCsFe8XhVWGxfsZWVJwvPDseXahFjIUXiEktFuXeSrbcg92PSmIWjlC94zsIMstDd3KG1XUFy56+U+x15lsmtG3J6zf0pweT4=